name: Docker Verify
on:
  push:
    branches:
      - "**"
      - "!main"
env:
  IMAGE: johnlindahl/sqlite
  # renovate: datasource=docker depName=alpine
  ALPINE_VERSION: 3.19.1
  # renovate: datasource=repology depName=alpine_3_18/sqlite
  SQLITE_VERSION: 3.41.2-r3
jobs:
  verify-install:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build server and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ env.IMAGE }}:test,${{ env.IMAGE }}:test-${{ env.SQLITE_VERSION }}-alpine-${{ env.ALPINE_VERSION }}
